admin_subscription_index:
  path: admin-subscription
  methods: GET
  defaults:
    _controller: Mollie\Subscription\Controller\Symfony\SubscriptionController::indexAction
    _legacy_controller: AdminMollieSubscriptionOrders
    _legacy_link: AdminMollieSubscriptionOrders

admin_subscription_delete:
  path: admin-subscription/{subscriptionId}/delete
  methods: POST
  defaults:
    _controller: Mollie\Subscription\Controller\Symfony\SubscriptionController::deleteAction
    _legacy_controller: AdminMollieSubscriptionOrders
    _legacy_link: AdminMollieSubscriptionOrders
  requirements:
    subscriptionId: \d+
