mollie_module_admin_resend_payment_message:
    path: /mollie/email/{orderId}/secondChance/send
    methods: [GET]
    defaults:
        _controller: 'Mollie\Controller\AdminMollieEmailController::sendSecondChanceMessage'
    requirements:
        orderId: "^[0-9]*"

admin_subscription_index:
    path: admin-subscription
    methods: GET
    defaults:
        _controller: Mollie\Subscription\Controller\Symfony\SubscriptionController::indexAction
        _legacy_controller: AdminMollieSubscriptionOrders
        _legacy_link: AdminMollieSubscriptionOrders

admin_subscription_edit:
    path: admin-subscription/{subscriptionId}/update
    methods: [GET, POST]
    defaults:
        _controller: Mollie\Subscription\Controller\Symfony\SubscriptionController::editAction
        _legacy_controller: AdminMollieSubscriptionOrders
        _legacy_link: AdminMollieSubscriptionOrders
    requirements:
        subscriptionId: \d+

admin_subscription_delete:
    path: admin-subscription/{subscriptionId}/delete
    methods: POST
    defaults:
        _controller: Mollie\Subscription\Controller\Symfony\SubscriptionController::deleteAction
        _legacy_controller: AdminMollieSubscriptionOrders
        _legacy_link: AdminMollieSubscriptionOrders
    requirements:
        subscriptionId: \d+
