services:
  _defaults:
    public: true

  Mollie:
    class: 'Mollie'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'mollie'

  Mollie\Subscription\Grid\SubscriptionGridQueryBuilder:
    class: Mollie\Subscription\Grid\SubscriptionGridQueryBuilder
    parent: 'prestashop.core.grid.abstract_query_builder'
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
    public: true

  Mollie\Subscription\Grid\SubscriptionGridDefinitionFactory:
    class: 'Mollie\Subscription\Grid\SubscriptionGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    arguments:
      - '@Mollie'
      - '@Mollie\Subscription\Grid\Accessibility\SubscriptionCancelAccessibility'
    public: true

  subscription_grid_data_factory:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@Mollie\Subscription\Grid\SubscriptionGridQueryBuilder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'invertus_mollie_subscription'

  subscription_grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@Mollie\Subscription\Grid\SubscriptionGridDefinitionFactory'
      - '@subscription_grid_data_factory'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  Mollie\Subscription\Grid\Accessibility\SubscriptionCancelAccessibility:
    class: Mollie\Subscription\Grid\Accessibility\SubscriptionCancelAccessibility

  Mollie\Subscription\RecurringOrder\RecurringOrderType:
    class: Mollie\Subscription\RecurringOrder\RecurringOrderType
    calls:
        - { method: setTranslator, arguments: ['@translator'] }
    tags:
      - { name: form.type }

  Mollie\Subscription\RecurringOrder\DataProvider\RecurringOrderFormDataProvider:
    class: Mollie\Subscription\RecurringOrder\DataProvider\RecurringOrderFormDataProvider
    arguments:
      - '@prestashop.core.query_bus'

  recurring_order_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'Mollie\Subscription\RecurringOrder\RecurringOrderType'
      - '@Mollie\Subscription\RecurringOrder\DataProvider\RecurringOrderFormDataProvider'

  recurring_order_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.data_handler.customer_form_data_handler'

  Mollie\Subscription\RecurringOrder\QueryHandler\GetRecurringOrderForViewingHandler:
    class: 'Mollie\Subscription\RecurringOrder\QueryHandler\GetRecurringOrderForViewingHandler'
    tags:
      - name: tactician.handler
        command: 'Mollie\Subscription\RecurringOrder\Query\GetRecurringOrderForViewing'
