name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: build
        run: |
          mkdir mollie
          find . ! -regex '.*/mollie' ! -regex '.' -exec cp -r '{}' mollie \;
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mollie
          path: |
            mollie
            !mollie/.git
            !mollie/.github
            !mollie/vendorBuilder
            !mollie/node_modules
            !mollie/tests
            !mollie/views/js/node_modules


