name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: build
        run: |
# Removing the files we dont need in build configuration
          rm -rf .git
          rm -rf .github
          rm -rf vendorBuilder
          rm -rf node_modules
          rm -rf tests
          rm -rf views/js/node_modules
          rm -rf vendor # todo - uncomment this
          mkdir mollie # Creating a subfolder which will store our files
          rsync -Rr ./ ./mollie # Copies everything to subfolder
          rm -rf bin,config,controllers,mails,sql,src,tests,translations,upgrade,vendor,views # All folders removed
          cd mollie && rm -rf mollie
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mollie
          path: |
            .


