name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prestashop-container:
    runs-on: ubuntu-latest
    container: prestashop/prestashop:latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          # create a network for containers to communicate
            docker network create prestashop-net
          # launch mysql 5.7 container
            docker run -ti --name some-mysql --network prestashop-net -e MYSQL_ROOT_PASSWORD=admin -p 3307:3306 -d mysql:5.7
          # launch prestashop container
            docker run -ti --name some-prestashop --network prestashop-net -e DB_SERVER=some-mysql -p 8080:80 -d prestashop/prestashop
  cypress-run:
    runs-on: ubuntu-latest
    # Docker image with Cypress pre-installed
    # https://github.com/cypress-io/cypress-docker-images/tree/master/included
    container: cypress/included:9.3.1
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm ci
          cypress run
