name: Cypress test run
on:
  pull_request:
    types: [opened, reopened]
jobs:
  Cypress-E2E:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - prestashop: 'PS1770'
    env:
      NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        shell: bash
      - run: unzip -qq -o ngrok-stable-linux-amd64.zip
        shell: bash
      - run: ./ngrok authtoken ${{ secrets.NGROK_TOKEN }}
        shell: bash
      - run: ./ngrok http -region=eu -subdomain=demoshop 8001 > ngrok.log &
        shell: bash
      - name: install composer
        run: composer i

      - name: install package
        run: npm ci & npx browserslist@latest --update-db

      - name: PS ${{ matrix.prestashop }} installing / Module Install and Uninstall testing / Running ${{ matrix.prestashop }} Cypress tests
        run: make e2eh
        #--parallel --record --key fe20a60a-0ac6-4956-a6e8-911aad86cb03
  
      - name: Archive videos and screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: videos_screenshots
          retention-days: 7
          path: |
            cypress/videos
            cypress/screenshots
