name: Regular midnight test runs
on:
  push:
    #shedule:
    # - cron:  '0 0 * * 5'
jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         # Set N number of parallel jobs you want to run tests on.
#         # Use higher number if you have slow tests to split them on more parallel jobs.
#         # Remember to update ci_node_index below to 0..N-1
#         ci_node_total: [7]
#         # set N-1 indexes for parallel jobs
#         # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
#         ci_node_index: [0, 1, 2, 3, 4, 5, 6, 7]
    steps:
    
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-node-modules
        with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Cypress E2E Test Run
        uses: actions/checkout@v2.3.4

      - name: Test a ngrok tunnel
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        steps:
          - uses: actions/checkout@v2
          - name: Run establish a ngrok tunnel
            id: test
            uses: vmactions/ngrok-tunnel@v0.0.1
            with:
              protocol: tcp
              port: 22

      - name: NPM install
        run: npm i

      - name: Run Cypress tests [PS16 | PS17 | PS177 (WIP)]
        run: npx cypress run --config videoUploadOnPasses=false --env demousername=${{ secrets.DEMO_USER }},demopassword=${{ secrets.DEMO_PASS }},FO_username=${{ secrets.MOLLIE_FO_USR }},FO_password=${{ secrets.MOLLIE_FO_PSW }},mollie_test_api_key=${{ secrets.MOLLIE_TEST_API_KEY }},mollie_test_profile_id=${{ secrets.MOLLIE_TEST_PROFILE_ID }}
        #--parallel --record --key fe20a60a-0ac6-4956-a6e8-911aad86cb03
        
      - name: Archive videos and screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: videos_screenshots
          retention-days: 1
          path: |
            cypress/videos
            cypress/screenshots
